[[redirects]]
  from = "/api/*"
  to = "https://api-erp-demo.ngrok.app/:splat"
  status = 200
  force = true
  headers = { 
    Access-Control-Allow-Origin = "https://sengroup-erp.netlify.app",
    Access-Control-Allow-Credentials = "true"
  }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200